Python 3.9 compatibility
Thread.isAlive() is deprecated in 3.8 and removed in 3.9:

    $ python3.8 -c 'import threading; t = threading.Thread(); t.isAlive()'
    <string>:1: DeprecationWarning: isAlive() is deprecated, use is_alive() instead

    $ python3.9 -c 'import threading; t = threading.Thread(); t.isAlive()'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    AttributeError: 'Thread' object has no attribute 'isAlive'

Fixes https://github.com/micheles/decorator/issues/75